### ISSUE TITLE
Update database button not working

### ISSUE THREAD

**Issue by Ivanuskask** [OfficialAhmed/Check-Game-Firmware#1]
Hi, when i run the 2.07 exe file app. window opens, but I see "0" current database entries and  "update database" button can not be , pressed. Running it on Win 7 and 10, same issue. Best regards. Ivan

**Comment by OfficialAhmed** [comment]
Thank you for reporting. Dropped v2.08 fixing this issue 



> Hi, when i run the 2.07 exe file app. window opens, but I see "0" current database entries and "update database" button can not be , pressed. Running it on Win 7 and 10, same issue. Best regards. Ivan
